### ISSUE TITLE
Change port automatically in next project folder

### ISSUE THREAD

**Issue by JARVIS-AI** [bismay4u/AppServer#2]
Thanks for the handy tools server app
Clean electron based app
I love it
it's very useful when you want a lot of web project that need to be served in browsers

For now I have a great suggestion, 
The port number for all of the folder when we open them are same
for example when we select the first folder in app, port will be 4612 and for next one is the same
beside the drag and drop that set the root folder of server
can you add this feature ?
It's very useful when we have to serve 5 folder in a same time and with this we can get think !

Thanks in ADV
btw,
Cool app
i spread this app in my university
hope this project give more stars, it deserve that
I have more idea to get this app a better and more featured app
but step by step is better roadmap.
also when i finished my project, i wanna work on this , i need time 
thanks

**Comment by bismay4u** [comment]
Hi,

Thank you for your appreciation.

Your suggestion is good and will add the same in next release.

Thank you
