### ISSUE TITLE
How to deploy it?

### ISSUE THREAD

**Issue by leandroramos** [bismay4u/AppServer#3]
I'm sorry for the newbie question, but how can I deploy the arrserver? Thank you.

**Comment by janbiasi** [comment]
I think this server isn't meant to get deployed but rather to quickly serve things from your Desktop as the description says ...

**Comment by bismay4u** [comment]
Like said above, this is a development support software, and not meant to be on production system.

That being said, I will consider this as a feature request and have a system which can be used to deploy to various servers in future.

Thank you
